# Generated by Django 5.2.8 on 2025-11-18 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='created_at',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='updated_at',
            new_name='ultima_actualicacion',
        ),
    ]
